name: Paradime Turbo CI

on:
  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          sleep 30
          exit 0
